### ISSUE TITLE
add the Pull Requests title in the table

### ISSUE THREAD

**Issue by ericLemanissier** [prince-chrismc/conan-center-index-pending-review#3]
Also, I'm not sure I understand the selection criteria, but is it right that PRs disappear from this list 24h after creation, if they get no review ? Wouldn't it be better to simply list all PR which have at least one approval, or no approval and no blocker, regardless of the creation date ?

**Comment by prince-chrismc** [comment]
Sadly I found that PRs with no reviews were either stale or blocked or both. Sometimes we leave "comments" which are **not** reviews so just checking for reviews fell short.

Scrapping the API, last 600 closed PRs, the mean reviews delay was less than five hours and the max was 18hrs... for a new PR to go unnoticed for over 24 hr seemed unrealistic at the time.

My assumption is that it's been "commented" an awaiting feedback

+1 for the title... I also want to add the dates see if I can get better stats later

**Comment by ericLemanissier** [comment]
Maybe use 24h after the last push/update, instead of 24h after PR creation ? That would allow PRs like https://github.com/conan-io/conan-center-index/pull/3923 and https://github.com/conan-io/conan-center-index/pull/3621 to be visible

**Comment by prince-chrismc** [comment]
The challenge is the definition of "update" in the github API

I absolutely agree this can be improved.

Looking at https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#get-a-pull-request example response

we have `r["head"]["sha"]` and `r["head"]["repo"]["commits_url"]` which would get the authored time of the last commit?

**Comment by prince-chrismc** [comment]
I am not crazy for the title in the table since it's available in the tool tip of the PR. 

![image](https://user-images.githubusercontent.com/16867443/103231735-91d1a880-4906-11eb-9bda-36c4e42e7451.png)

Let me know what you think

**Comment by ericLemanissier** [comment]
maybe use the most recent between PR creation date and `r["head"]["repo"]["pushed_at"]` ?

**Comment by ericLemanissier** [comment]
Regarding the titles, they are surprisingly cut at 12 characters ?!

**Comment by prince-chrismc** [comment]
that time is for all branches + tags, if the user has multiple branches or the bincrafters mono fork, it wouldn't be accurate

yes! I disliked how wide the column was. Scrolling on the table to see who's names approved made bothered me too much

**Comment by ericLemanissier** [comment]
It's a question of priority and personal taste. I feel I'm more likely to choose the PR I'm going to review based on their title than based on who approved it. 
You could gain some space by removing the first column and put the links on the PRs titles

**Comment by prince-chrismc** [comment]
> I feel I'm more likely to choose the PR I'm going to review based on their title than based on who approved/authored it.

Yes... but I reviewed almost every PR on the list so I try to find the ones I did not review

> It's a question of priority and personal taste. 

💯 but I think we can find a compromise that works for everyone!

**Comment by prince-chrismc** [comment]
What information are you looking for from the title?

**Comment by ericLemanissier** [comment]
mainly the package name, so it is ok currently. It could have been handy to use the title as a short summary, but it's not as important, especially because we can get it by hovering the mouse over the link.
