### ISSUE TITLE
bot stuck

### ISSUE THREAD

**Issue by ericLemanissier** [prince-chrismc/conan-center-index-pending-review#49]
it looks like the bot does not work since few hours:
https://github.com/prince-chrismc/conan-center-index-pending-review/runs/5637795666?check_suite_focus=true#step:6:6

`Problem getting rate limit information GET https://api.github.com/rate_limit: 401 Bad credentials []`

**Comment by prince-chrismc** [comment]
I updated the token should be working again 🤞

**Comment by ericLemanissier** [comment]
thanks !

**Comment by ericLemanissier** [comment]
The issue is back !

**Comment by prince-chrismc** [comment]
Thank for bringing it to my attention!
