### ISSUE TITLE
Update table every 10 minutes

### ISSUE THREAD

**Issue by mathbunnyru** [prince-chrismc/conan-center-index-pending-review#5]
What do you think about updating the table not every 24 hours, but every 10 minutes?

This way, the merged PRs will disappear faster, and the PRs which waited for > 24 hours will really wait maximum for 24h10min.

Two downsides:
- the number of queries allowed.
- we need to be careful with notifications about changes - if nothing has changed, there should be no notification.

**Comment by prince-chrismc** [comment]
There's not enough activity in 10 minutes... its 1000 requests every hour so I doubt that will be the biggest limitation (it's about ~2.1 API requests per PR) 

There's no notification as of now 😕 not sure what you meant there.

Would once an hour be a good compromise? The bot will only merge once every 30 minutes

**Comment by mathbunnyru** [comment]
One hour would be great, sure.

> There's no notification as of now 😕 not sure what you meant there.

I mean, if someone subscribes to the issue, they might get notified every time the page is changed.
AFAIK, It doesn't always work as expected if the change to the message is done via API.

**Comment by prince-chrismc** [comment]
It's an edit so there is no notification from GitHub that I know of.

I'll update the cron job when I get back but feel free to open a PR in the mean time!

**Comment by ericLemanissier** [comment]
Yes, the problem with notifications I have in mind is happening in the android github app. I had to do an explicit verification before each post update [here](https://github.com/ericLemanissier/conan-center-conflicting-prs/blob/main/main.py#L157) in order to avoid notifying everybody each time the bot ran

**Comment by prince-chrismc** [comment]
Ahhh thank you! i never used the app but that makes sense

**Comment by prince-chrismc** [comment]
Looks like it's working 🎉
