### ISSUE TITLE
Ready To merge section

### ISSUE THREAD

**Issue by ericLemanissier** [prince-chrismc/conan-center-index-pending-review#6]
That's a very nice addition, but you should count only approved reviewers (listed in https://github.com/conan-io/conan-center-index/issues/2857#issue-695900291), otherwise prs like https://github.com/conan-io/conan-center-index/pull/4079  are marked as ready to merge, whereas they are still missing some reviews.

EDIT: also, could you add a column giving [the status of the PR (success./failure/pending)](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-commit-status) ?

**Comment by prince-chrismc** [comment]
Thank for for the issue ❤️ I saw it last night but I didn't see an obvious solution

I was thinking a JSON list which would be easy. Any Ideas?

**Comment by ericLemanissier** [comment]
I was thinking dumb full text search in https://github.com/conan-io/conan-center-index/issues/2857#issue-695900291

**Comment by prince-chrismc** [comment]
Hmmm there have been a few failures post code review changes, it's worth noting 🤔 

Out of curiosity how does it impact your decision to review?

**Comment by ericLemanissier** [comment]
I won't take a look to any PR which already has sufficient reviews (except cases were I have a direct interest in the package). It saves both my time, and also useless notifications to everybody else. I have the same reasoning for PR with a failed status

**Comment by prince-chrismc** [comment]
I find the stability unreliable, if there's a fail there's usually a label and I filter on that... however the case were CI is stuck might be interesting

**Comment by ericLemanissier** [comment]
Ok, I did not know you filtered on labels. The only missing case is if the contributor did not request access on https://github.com/conan-io/conan-center-index/issues/4  (which makes https://github.com/conan-io/conan-center-index/pull/3724 ready to be merged)

**Comment by prince-chrismc** [comment]
No the "No beta" label was removed... its the CI that's failed and no one has restarted hence https://github.com/prince-chrismc/conan-center-index-pending-review/issues/6#issuecomment-759455677 above

**Comment by prince-chrismc** [comment]
https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#statuses 

Supposedly support by underlying library

**Comment by prince-chrismc** [comment]
Found it!

https://api.github.com/repos/conan-io/conan-center-index/statuses/15ccdabe9b96b52ab42e419eb9e2ce62c6c3bf62?per_page=1

**Comment by prince-chrismc** [comment]
Yay or nay?

![image](https://user-images.githubusercontent.com/16867443/104858149-413ce200-58eb-11eb-9a2a-2a99fc60a5e2.png)

**Comment by ericLemanissier** [comment]
thank you, it's perfect !
