### ISSUE TITLE
use upstream information directly

### ISSUE THREAD

**Issue by ericLemanissier** [prince-chrismc/conan-center-index-pending-review#62]
Reviewers (team AND community) are now all listed in https://github.com/conan-io/conan-center-index/blob/master/.c3i/reviewers.yml
Also, the number of reviews required before merge is in https://github.com/conan-io/conan-center-index/blob/master/.c3i/c3i.yml tasks->automatic_merge

**Comment by prince-chrismc** [comment]
Looking into this for an afternoon project, I noted YAML is not in the Golang encoding package... and parsing a large struct for a few fields seems to be problematic for most libraries...

Stumbled on this https://stackoverflow.com/questions/40737122/convert-yaml-to-json-without-struct which seems like it could be used to get the one item

The second one is "easy" but not trivial 🤞 

## To Do List

- [ ] Pick a YAML library
- [ ] struct defintion for reviewers
- [ ] update matching

**Comment by ericLemanissier** [comment]
I don't know go (at all), but a quick search directs me to https://github.com/go-yaml/yaml
